countries = [
    'Afghanistan',
    'Burkina Faso',
    'Burundi',
    'Cameroon',
    'Central African Republic',
    'Chad',
    'Democratic Republic of the Congo',
    'Ethiopia',
    'Haiti',
    'Iraq',
    'Libya',
    'Mali',
    'Myanmar',
    'Niger',
    'Nigeria',
    'Occupied Palestinian Territory',
    'Somalia',
    'South Sudan',
    'Sudan',
    'Syria',
    'Ukraine',
    'Venezuela',
    'Yemen',
]

palestine_country_code = 'PSE'
