# prod
spreadsheet_url: "https://docs.google.com/spreadsheets/d/1RNSC1FrYfprR2lY_XftGlSSLujYRizzYZd1zmelUPNY/edit"
# test
# spreadsheet_url: "https://docs.google.com/spreadsheets/d/1iBdFVrmianGnrPq_cfHt83xR1kVb_OBETwQlHUUr5E8/edit"
indicator_sheetname: "Indicator"
timeseries_sheetname: "Timeseries"
cumulative_sheetname: "Cumulative"

countries:
  - "Afghanistan"
  - "Burkina Faso"
  - "Burundi"
  - "Cameroon"
  - "Central African Republic"
  - "Chad"
  - "Colombia"
  - "Democratic Republic of the Congo"
  - "Ethiopia"
  - "Haiti"
  - "Iraq"
  - "Libya"
  - "Mali"
  - "Myanmar"
  - "Niger"
  - "Nigeria"
  - "occupied Palestinian territory"
  - "Somalia"
  - "South Sudan"
  - "Sudan"
  - "Syria"
  - "Ukraine"
  - "Venezuela"
  - "Yemen"
  - "Zimbabwe"